### ISSUE TITLE
not all arguments converted during string formatting

### ISSUE THREAD

**Issue by Ageotas** [ACMILabs/tripadvisor-scraper#7]
When replacing the tripadvisor url to that of another institution, the following TypeError is produced:

`2018-06-06 22:30:21 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-06-06 22:30:21 [scrapy.utils.log] INFO: Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 18.4.0, Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) - [GCC 7.3.0], pyOpenSSL 18.0.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Linux-4.4.0-17134-Microsoft-x86_64-with-Ubuntu-18.04-bionic
Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/ageotas/.local/lib/python2.7/site-packages/scrapy/cmdline.py", line 150, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/ageotas/.local/lib/python2.7/site-packages/scrapy/cmdline.py", line 90, in _run_print_help
    func(*a, **kw)
  File "/home/ageotas/.local/lib/python2.7/site-packages/scrapy/cmdline.py", line 157, in _run_command
    cmd.run(args, opts)
  File "/home/ageotas/.local/lib/python2.7/site-packages/scrapy/commands/runspider.py", line 80, in run
    module = _import_file(filename)
  File "/home/ageotas/.local/lib/python2.7/site-packages/scrapy/commands/runspider.py", line 21, in _import_file
    module = import_module(fname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/mnt/c/Users/Ageotas/Desktop/Scitech/ReviewScraper/tripadvisor-scraper/tripadvisorscraper.py", line 19, in <module>
    class TripAdvisorReview(scrapy.Spider):
  File "/mnt/c/Users/Ageotas/Desktop/Scitech/ReviewScraper/tripadvisor-scraper/tripadvisorscraper.py", line 21, in TripAdvisorReview
    start_urls = list(url_generator())
  File "/mnt/c/Users/Ageotas/Desktop/Scitech/ReviewScraper/tripadvisor-scraper/tripadvisorscraper.py", line 16, in url_generator
    yield URL_TEMPLATE % (page * 10)
TypeError: not all arguments converted during string formatting`

**Comment by Ageotas** [comment]
User error; was missing the or%s in the URL_TEMPLATE
